name: Build
on: [workflow_call]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ghcr.io/yeetari/vull:master
    strategy:
      fail-fast: false
      matrix:
        preset: [debug-gcc, release-clang, release-gcc]
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        shell: bash
        run: >-
          cmake .
          --preset ${{ matrix.preset }}
          -Bbuild
          -DCMAKE_COMPILE_WARNING_AS_ERROR=ON
          $( [[ ${{ matrix.preset }} == debug-gcc ]] && echo -DVULL_ENABLE_COVERAGE=ON )
          -GNinja

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: cmake --build build --target test

      - name: Generate coverage report
        if: ${{ matrix.preset == 'debug-gcc' }}
        run: cmake --build build --target coverage.xml

      - name: Upload coverage summary report
        if: ${{ matrix.preset == 'debug-gcc' }}
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: build/coverage.xml
          badge: true
          format: markdown
          output: both
          hide_complexity: true

      - name: Add coverage comment
        if: ${{ matrix.preset == 'debug-gcc' && github.event_name == 'pull_request' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-results.md
