name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ubuntu:22.10
    env:
      DEBIAN_FRONTEND: noninteractive
    strategy:
      fail-fast: false
      matrix:
        preset: [release-clang, release-gcc]
    steps:
      - name: Update package lists
        run: apt update -qq
      - name: Add vulkan-sdk repository
        run: |
          apt install -y gnupg2 wget
          wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | apt-key add -
          wget -qO /etc/apt/sources.list.d/lunarg-vulkan-focal.list http://packages.lunarg.com/vulkan/lunarg-vulkan-focal.list
          apt update -qq
      - name: Install tools and dependencies
        run: >-
          apt install -y
          clang
          cmake
          gcc
          g++
          git
          libfreetype-dev
          libharfbuzz-dev
          libx11-dev
          libxcb-randr0-dev
          libxcb-util-dev
          libxcb-xkb-dev
          libzstd-dev
          ninja-build
          shaderc
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure CMake
        run: >-
          cmake .
          --preset ${{ matrix.preset }}
          -Bbuild
          -DCMAKE_COMPILE_WARNING_AS_ERROR=On
          -DVULL_BUILD_GLTF=On
          -DVULL_BUILD_SANDBOX=On
          -DVULL_BUILD_TESTS=On
          -GNinja
      - name: Build
        run: cmake --build build
      - name: Run tests
        run: ./build/engine/vull-tests
