name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ghcr.io/yeetari/vull:master
    strategy:
      fail-fast: false
      matrix:
        preset: [release-clang, release-gcc]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure CMake
        run: >-
          cmake .
          --preset ${{ matrix.preset }}
          -Bbuild
          -DCMAKE_COMPILE_WARNING_AS_ERROR=On
          -DVULL_BUILD_GLTF=On
          -DVULL_BUILD_PNG=On
          -DVULL_BUILD_SANDBOX=On
          -DVULL_BUILD_TESTS=On
          -GNinja
      - name: Build
        run: cmake --build build
      - name: Run tests
        run: cmake --build build --target test
