name: Build
on: [workflow_call]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ghcr.io/yeetari/vull:master
    strategy:
      fail-fast: false
      matrix:
        preset: [release-clang, release-gcc]
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: >-
          cmake .
          --preset ${{ matrix.preset }}
          -Bbuild
          -DCMAKE_COMPILE_WARNING_AS_ERROR=ON
          -GNinja

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: cmake --build build --target test
