name: CI Runner
on: [push, pull_request]

permissions: write-all

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-runner
  cancel-in-progress: true

jobs:
  code-style:
    name: Code Style
    uses: ./.github/workflows/code_style.yml

  static-analysis:
    name: Static Analysis
    needs: code-style
    uses: ./.github/workflows/static_analysis.yml

  build:
    name: Build
    needs: static-analysis
    uses: ./.github/workflows/build.yml
    secrets: inherit
