name: Static Analysis
on: [push, pull_request]
jobs:
  clang-tidy:
    name: Clang Tidy
    runs-on: ubuntu-latest
    container: ubuntu:21.10
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Update package lists
        run: apt update -qq
      - name: Add cmake and vulkan-sdk repositories
        run: |
          apt install -y gnupg2 wget
          wget -qO - https://apt.kitware.com/keys/kitware-archive-latest.asc | apt-key add -
          wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | apt-key add -
          echo 'deb https://apt.kitware.com/ubuntu focal main' > /etc/apt/sources.list.d/kitware.list
          wget -qO /etc/apt/sources.list.d/lunarg-vulkan-focal.list http://packages.lunarg.com/vulkan/lunarg-vulkan-focal.list
          apt update -qq
      - name: Install tools and dependencies
        run: >-
          apt install -y
          clang
          clang-tidy
          cmake
          git
          libx11-dev
          libxcb-util-dev
          parallel
          vulkan-sdk
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure CMake
        run: cmake . -Bbuild -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - name: Run clang-tidy
        run: |
          find engine/sources sandbox \
            -name '*.cc' \
            -and -not -name 'ContextTable.cc' \
            -print0 |
          parallel -0 \
            clang-tidy -p build --header-filter=vull/ --quiet {} 2>/dev/null |
          tee output
          if [ -s output ]; then exit 1; fi
