name: Static Analysis
on: [push, pull_request]
jobs:
  clang-tidy:
    name: Clang Tidy
    runs-on: ubuntu-latest
    container: ghcr.io/yeetari/vull:master
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake . --preset debug-clang -Bbuild
      - name: Run clang-tidy
        run: |
          find engine/sources sandbox \
            -name '*.cc' \
            -print0 |
          parallel -0 \
            clang-tidy -p build --header-filter=vull/ --quiet {} 2>/dev/null |
          tee output
          if [ -s output ]; then exit 1; fi
